# docker-compose -f gitea-compose.yml up -d, after stop/start...
version: "3"

# docker network create --gateway 172.16.1.1 --subnet 172.16.1.0/24 mynetwork
# docker run -itd --privileged --net mynetwork --ip 172.16.1.2 --name gitea -p 9080:8080 -p 20022:22 lanovia/rocky-8.7-ssh

# start/down
# docker-compose -f cicd-docker.yml up -d
# docker-compose -f cicd-docker.yml down
services:
  cicd:
    container_name: gitea
    image: gitea/gitea:1.19.3
    environment:
      - TZ=Asia/Seoul
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=mariadb:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    networks:
      network:
        ipv4_address: 172.16.1.2
    restart: always
    volumes:
      - /d/docker-volume/cicd/gitea/var/lib/gitea:/var/lib/gitea
      - /d/docker-volume/cicd/gitea/etc/gitea:/etc/gitea      
      #- /d/docker-volume/cicd/gitea/etc/timezone:/etc/timezone:ro
      #- /d/docker-volume/cicd/gitea/etc/localtime:/etc/localtime:ro
    ports:
      - 9080:3000
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    image: mariadb:10.6.13
    restart: always
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea    
    
    networks:
      network:
        ipv4_address: 172.16.1.3
    volumes:
      #- /d/docker-volume/cicd/mariadb/etc/mysql/conf.d:/etc/mysql/conf.d
      - /d/docker-volume/cicd/mariadb/var/lib/mysql:/var/lib/mysql
    ports:
      - 3306:3306

networks:
  network:
    external: false
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24
          gateway: 172.16.1.1
